# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0e4164f19a5aec7a5a5a527e43ff46e815d272acc9ed73f38f9d09f4438d806ad9600918ebe6dfe535d736a2b9edd78130212face13a854b0754b77cae44aa8

test:
  secret_key_base: 65a1b72053e7925d88faf8eeff4f6994f33096ff262d22bc67b0e08e9fd7111a9f4295c043629b46949ed02f51e2bbf7184a6aced91000d88f0abaafce2571b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
